#!/bin/bash

# Prefer US English and use UTF-8 encoding.

export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"

# editors
export EDITOR=code
export GIT_EDITOR=nano

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# keep history up to date, across sessions, in realtime
# http://unix.stackexchange.com/a/48113
export HISTCONTROL=ignoredups:erasedups         # no duplicate entries
export HISTSIZE=100000                          # big big history (default is 500)
export HISTFILESIZE=$HISTSIZE                   # big big history
export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:* --help" # Don't add certain commands to the history file.
which shopt > /dev/null && shopt -s histappend  # append to history, don't overwrite it

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export PATH="$PATH:$HOME/.yarn/bin"

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
