# disable oh my zsh auto updates
DISABLE_AUTO_UPDATE="true"

source ~/zgen/zgen.zsh

# if the init scipt doesn't exist
if ! zgen saved; then
	printf "$(tput setaf 7)Creating a zgen save...\033[m\n"

	zgen oh-my-zsh

	zgen oh-my-zsh lib/completion.zsh
	zgen oh-my-zsh lib/git.zsh
	zgen oh-my-zsh lib/history.zsh
	zgen oh-my-zsh lib/spectrum.zsh
	zgen oh-my-zsh lib/theme-and-appearance.zsh

	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/colored-man-pages
	zgen oh-my-zsh plugins/virtualenvwrapper
    zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/npm
    zgen oh-my-zsh plugins/brew
    zgen oh-my-zsh plugins/vagrant
    zgen oh-my-zsh plugins/z

	# this must be the last loaded
	zgen load zsh-users/zsh-syntax-highlighting
	zgen load oskarkrawczyk/honukai-iterm-zsh honukai.zsh-theme

	open .zgen/oskarkrawczyk/honukai-iterm-zsh-master/honukai.itermcolors

  	# generate the init script from plugins above
  	zgen save
fi

# Load the shell dotfiles, and then some:
for file in ~/.{shell_aliases,shell_exports,shell_functions}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
